# Generated by Django 5.1.7 on 2025-03-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EggProductionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("eggs_produced", models.PositiveIntegerField()),
                ("eggs_sold", models.PositiveIntegerField()),
                (
                    "eggs_remaining",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
    ]
