# Generated by Django 5.1.7 on 2025-03-15 12:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EggSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("buyer_name", models.CharField(max_length=255)),
                ("eggs_sold", models.PositiveIntegerField()),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.AlterField(
            model_name="eggproductionrecord",
            name="date",
            field=models.DateField(default=django.utils.timezone.now, unique=True),
        ),
        migrations.AlterField(
            model_name="eggproductionrecord",
            name="eggs_sold",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
