# Generated by Django 5.1.7 on 2025-03-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0002_eggsale_alter_eggproductionrecord_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eggproductionrecord",
            name="manual_stock_entry",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eggproductionrecord",
            name="eggs_sold",
            field=models.PositiveIntegerField(),
        ),
    ]
