# Generated by Django 5.1.7 on 2025-03-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0003_eggproductionrecord_manual_stock_entry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eggproductionrecord",
            name="remark",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eggproductionrecord",
            name="eggs_sold",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
